# Generated by Django 4.1.5 on 2023-02-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254)),
                ('qualification', models.CharField(choices=[('10th', 'Matic pass or Above'), ('12th', '12th pass'), ('UG', 'Under graduate'), ('PG', 'Post graduate')], max_length=10)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
