# Generated by Django 4.1.5 on 2023-02-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='address',
            field=models.CharField(max_length=200, verbose_name='ADDRESS'),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='email_id',
            field=models.EmailField(blank=True, default=' ', max_length=254, null=True, verbose_name='EMAIL_ID'),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='name',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='NAME'),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='qualification',
            field=models.CharField(choices=[('10th', 'Matic pass or Above'), ('12th', '12th pass'), ('UG', 'Under graduate'), ('PG', 'Post graduate')], max_length=10, verbose_name='QUALIFICATION'),
        ),
    ]
