# Generated by Django 4.1.5 on 2023-02-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_management', '0003_alter_admin_password_alter_admin_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='qualification',
            field=models.CharField(choices=[('10th', 'Matic pass or Above'), ('12th', '12th pass'), ('UG', 'Under graduate'), ('PG', 'Post graduate'), ('PHD', 'Doctor of Philosophy')], max_length=10, verbose_name='QUALIFICATION'),
        ),
    ]
