# Generated by Django 4.1.5 on 2023-02-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_management', '0004_alter_admin_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='UserName')),
                ('password', models.CharField(max_length=8, verbose_name='Password')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
