# Generated by Django 4.1.5 on 2023-02-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_management', '0005_admin_panel_delete_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='qualification',
            field=models.CharField(choices=[('10th', 'Matic pass or Below'), ('12th', '12th pass'), ('UG', 'Under graduate'), ('PG', 'Post graduate'), ('PHD', 'Doctor of Philosophy')], max_length=10, verbose_name='QUALIFICATION'),
        ),
    ]
